use crate::monitor::push_job::WeakOutcomeKind;
use sha2::{Digest, Sha256};
use std::sync::atomic::{AtomicU64, Ordering};

use super::NotificationChannel;

static NEXT_SEND: AtomicU64 = AtomicU64::new(0);

fn next_send_id() -> String {
    format!(
        "notification-send-{}-{:x}-{:x}",
        chrono::Utc::now().timestamp_nanos_opt().unwrap_or_default(),
        std::process::id(),
        NEXT_SEND.fetch_add(1, Ordering::Relaxed)
    )
}

/// One built Reqwest HTTP entity for one configured target. URLs, headers,
/// body bytes, and credentials are intentionally excluded from this record.
/// It does not observe redirects, TLS bytes, or a remote delivery receipt.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NotificationRequestEntity {
    target_sha256: String,
    body_sha256: String,
    body_len: usize,
    response_url_sha256: Option<String>,
}

impl NotificationRequestEntity {
    fn digest_target(url: &str) -> String {
        let mut target = Sha256::new();
        target.update(b"stock_analysis.notification_target_url.v1\0");
        target.update(url.as_bytes());
        format!("{:x}", target.finalize())
    }

    fn digest_body(body: &[u8]) -> String {
        let mut entity = Sha256::new();
        entity.update(b"stock_analysis.notification_http_entity.v1\0");
        entity.update(body);
        format!("{:x}", entity.finalize())
    }

    pub(super) fn from_built_request(request: &reqwest::Request) -> Option<Self> {
        let body = request.body()?.as_bytes()?;
        Some(Self {
            target_sha256: Self::digest_target(request.url().as_str()),
            body_sha256: Self::digest_body(body),
            body_len: body.len(),
            response_url_sha256: None,
        })
    }

    /// The response URL is observable only when Reqwest returns a response.
    /// It identifies the final response target after redirects, not the body
    /// or method Reqwest sent on any redirected hop.
    pub(super) fn observe_response_url(&mut self, url: &reqwest::Url) {
        self.response_url_sha256 = Some(Self::digest_target(url.as_str()));
    }

    /// Verify the exact JSON entity generated by the Custom webhook path for
    /// a report. This binds a weak attempt to the report bytes before a local
    /// receipt can be persisted; it cannot prove the CLI invocation identity.
    pub fn matches_custom_content(&self, content: &str) -> bool {
        let body = serde_json::json!({ "content": content });
        let bytes = serde_json::to_vec(&body).expect("JSON string body serializes");
        self.body_len == bytes.len() && self.body_sha256 == Self::digest_body(&bytes)
    }

    pub fn target_sha256(&self) -> &str {
        &self.target_sha256
    }

    pub fn body_sha256(&self) -> &str {
        &self.body_sha256
    }

    pub fn body_len(&self) -> usize {
        self.body_len
    }

    pub fn response_url_sha256(&self) -> Option<&str> {
        self.response_url_sha256.as_deref()
    }

    /// A false value does not exclude a redirect that returned to the initial URL.
    pub fn response_target_differs(&self) -> Option<bool> {
        self.response_url_sha256
            .as_ref()
            .map(|response| response != &self.target_sha256)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NotificationCompletion {
    NoTargets,
    AllFailed,
    Partial,
    AllAccepted,
}

/// One actual notification target observed during a single send_report call.
///
/// target_index is only its zero-based position in this invocation. It is not
/// a durable target identity and must not be used for retry or recovery.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NotificationAttempt {
    channel: NotificationChannel,
    target_index: usize,
    outcome: WeakOutcomeKind,
    request_entity: Option<NotificationRequestEntity>,
}

impl NotificationAttempt {
    pub(super) fn new(
        channel: NotificationChannel,
        target_index: usize,
        outcome: WeakOutcomeKind,
        request_entity: Option<NotificationRequestEntity>,
    ) -> Self {
        Self {
            channel,
            target_index,
            outcome,
            request_entity,
        }
    }

    pub fn channel(&self) -> NotificationChannel {
        self.channel
    }

    pub fn target_index(&self) -> usize {
        self.target_index
    }

    pub fn outcome(&self) -> WeakOutcomeKind {
        self.outcome
    }

    pub fn request_entity(&self) -> Option<&NotificationRequestEntity> {
        self.request_entity.as_ref()
    }
}

/// Read-only weak observations from one real notification send invocation.
///
/// Accepted means only that an existing channel method returned its weak
/// success value. It does not prove the full original content was sent, that a
/// user read it, that every required target completed, or that delivery is
/// idempotent across restarts. This report is not durable completion evidence.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NotificationSendReport {
    send_id: String,
    attempts: Vec<NotificationAttempt>,
}

impl Default for NotificationSendReport {
    fn default() -> Self {
        Self {
            send_id: next_send_id(),
            attempts: Vec::new(),
        }
    }
}

impl NotificationSendReport {
    pub(super) fn from_attempts(attempts: Vec<NotificationAttempt>) -> Self {
        Self {
            send_id: next_send_id(),
            attempts,
        }
    }

    /// Distinguishes two physical send_report invocations, including repeats
    /// of an otherwise identical report. This is not an idempotency key.
    pub fn send_id(&self) -> &str {
        &self.send_id
    }

    pub fn attempts(&self) -> &[NotificationAttempt] {
        &self.attempts
    }

    pub fn has_success(&self) -> bool {
        self.accepted_count() > 0
    }

    pub fn accepted_count(&self) -> usize {
        self.attempts
            .iter()
            .filter(|attempt| attempt.outcome == WeakOutcomeKind::Accepted)
            .count()
    }

    pub fn unknown_count(&self) -> usize {
        self.attempts.len().saturating_sub(self.accepted_count())
    }

    pub fn completion(&self) -> NotificationCompletion {
        match (self.accepted_count(), self.unknown_count()) {
            (0, 0) => NotificationCompletion::NoTargets,
            (0, _) => NotificationCompletion::AllFailed,
            (_, 0) => NotificationCompletion::AllAccepted,
            _ => NotificationCompletion::Partial,
        }
    }
}
