use crate::portfolio::closing_valuation::{ClosingValuation, ClosingValuationItem, ClosingValuationItemStatus};
use diesel::prelude::*;
use sha2::{Digest, Sha256};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SaveClosingValuationReceipt { pub run_id: String, pub inserted: bool }
#[derive(Debug, Clone, PartialEq)]
pub struct ClosingValuationView { pub persisted_run_row_id: i64, pub valuation: ClosingValuation }

pub fn create_schema(conn: &mut SqliteConnection) -> Result<(), String> {
    for sql in [
        "CREATE TABLE IF NOT EXISTS closing_valuation_run (id INTEGER PRIMARY KEY AUTOINCREMENT, run_id TEXT NOT NULL UNIQUE, snapshot_id TEXT NOT NULL, price_date TEXT NOT NULL, calculation_version TEXT NOT NULL, provider TEXT NOT NULL, valued_count INTEGER NOT NULL, total_count INTEGER NOT NULL, total_market_value REAL, total_unrealized_pnl REAL, UNIQUE(snapshot_id,price_date,calculation_version))",
        "CREATE TABLE IF NOT EXISTS closing_valuation_item (run_id TEXT NOT NULL REFERENCES closing_valuation_run(run_id), code TEXT NOT NULL, name TEXT NOT NULL, quantity INTEGER NOT NULL, cost_price REAL NOT NULL, close REAL, market_value REAL, unrealized_pnl REAL, unrealized_return_pct REAL, daily_price_pnl REAL, reason_code TEXT, PRIMARY KEY(run_id,code))",
        "CREATE TRIGGER IF NOT EXISTS closing_valuation_run_no_update BEFORE UPDATE ON closing_valuation_run BEGIN SELECT RAISE(ABORT, 'closing_valuation_run is append-only'); END",
        "CREATE TRIGGER IF NOT EXISTS closing_valuation_run_no_delete BEFORE DELETE ON closing_valuation_run BEGIN SELECT RAISE(ABORT, 'closing_valuation_run is append-only'); END",
        "CREATE TRIGGER IF NOT EXISTS closing_valuation_item_no_update BEFORE UPDATE ON closing_valuation_item BEGIN SELECT RAISE(ABORT, 'closing_valuation_item is append-only'); END",
        "CREATE TRIGGER IF NOT EXISTS closing_valuation_item_no_delete BEFORE DELETE ON closing_valuation_item BEGIN SELECT RAISE(ABORT, 'closing_valuation_item is append-only'); END",
    ] { diesel::sql_query(sql).execute(conn).map_err(|e|e.to_string())?; } Ok(())
}

fn deterministic_run_id(v:&ClosingValuation)->String { let mut h=Sha256::new(); h.update(b"stock_analysis.closing_valuation.v1\0"); h.update(format!("{}|{}|{}",v.snapshot_id,v.price_date,v.calculation_version).as_bytes()); format!("cv_v1_{:x}",h.finalize()) }

pub fn save_closing_valuation(v:&ClosingValuation)->Result<SaveClosingValuationReceipt,String>{ let run_id=deterministic_run_id(v); let db=crate::database::DatabaseManager::get(); let mut conn=db.get_conn().map_err(|e|e.to_string())?; conn.transaction(|c|{ let ex:Option<(i64,)> = diesel::sql_query("SELECT id FROM closing_valuation_run WHERE run_id=?").bind::<diesel::sql_types::Text,_>(&run_id).get_result(c).optional().map_err(|e|e.to_string())?; if let Some((_id,))=ex{return Ok(SaveClosingValuationReceipt{run_id,inserted:false})} diesel::sql_query("INSERT INTO closing_valuation_run(run_id,snapshot_id,price_date,calculation_version,provider,valued_count,total_count,total_market_value,total_unrealized_pnl) VALUES (?,?,?,?,?,?,?,?,?)").bind::<diesel::sql_types::Text,_>(&run_id).bind::<diesel::sql_types::Text,_>(&v.snapshot_id).bind::<diesel::sql_types::Text,_>(v.price_date.to_string()).bind::<diesel::sql_types::Text,_>(&v.calculation_version).bind::<diesel::sql_types::Text,_>(&v.provider).bind::<diesel::sql_types::Integer,_>(v.valued_count as i32).bind::<diesel::sql_types::Integer,_>(v.total_count as i32).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(v.total_market_value).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(v.total_unrealized_pnl).execute(c).map_err(|e|e.to_string())?; for i in &v.items { let (close,mv,pnl,ret,dp,reason)=match &i.status { ClosingValuationItemStatus::Valued{close,market_value,unrealized_pnl,unrealized_return_pct,daily_price_pnl,..}=>(*close,Some(*market_value),Some(*unrealized_pnl),Some(*unrealized_return_pct),Some(*daily_price_pnl),None), ClosingValuationItemStatus::Unavailable{reason_code}=>(0.0,None,None,None,None,Some(reason_code.as_str()))}; diesel::sql_query("INSERT INTO closing_valuation_item(run_id,code,name,quantity,cost_price,close,market_value,unrealized_pnl,unrealized_return_pct,daily_price_pnl,reason_code) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind::<diesel::sql_types::Text,_>(&run_id).bind::<diesel::sql_types::Text,_>(&i.code).bind::<diesel::sql_types::Text,_>(&i.name).bind::<diesel::sql_types::BigInt,_>(i.quantity as i64).bind::<diesel::sql_types::Double,_>(i.cost_price).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(if reason.is_none(){Some(close)}else{None}).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(mv).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(pnl).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(ret).bind::<diesel::sql_types::Nullable<diesel::sql_types::Double>,_>(dp).bind::<diesel::sql_types::Nullable<diesel::sql_types::Text>,_>(reason).execute(c).map_err(|e|e.to_string())?; } Ok(SaveClosingValuationReceipt{run_id,inserted:true}) }) }

pub fn latest_persisted_valuation_view()->Result<Option<ClosingValuationView>,String>{ Ok(None) }
