//! Generated by refactor stage 2 — extracted from src/search_service.rs

use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use async_trait::async_trait;
use log::{debug, error, info, warn};
use serde::{Deserialize, Serialize};

use super::super::types::{extract_domain, ApiKeyManager, NewsType, SearchProvider, SearchResponse, SearchResult, Sentiment};


// ============================================================================
// Bocha 搜索引擎
// ============================================================================

/// Bocha 搜索引擎
///
/// 特点：
/// - 专为AI优化的中文搜索API
/// - 结果准确、摘要完整
/// - 支持时间范围过滤和AI摘要
/// - 兼容Bing Search API格式
///
/// 文档：https://bocha-ai.feishu.cn/wiki/RXEOw02rFiwzGSkd9mUcqoeAnNK
pub struct BochaSearchProvider {
    name: String,
    key_manager: Arc<Mutex<ApiKeyManager>>,
    client: reqwest::Client,
}

impl BochaSearchProvider {
    pub fn new(api_keys: Vec<String>) -> Self {
        Self {
            name: "Bocha".to_string(),
            key_manager: Arc::new(Mutex::new(ApiKeyManager::new(api_keys))),
            client: reqwest::Client::new(),
        }
    }

    async fn do_search(&self, query: &str, api_key: &str, max_results: usize) -> Result<SearchResponse> {
        #[derive(Serialize)]
        struct BochaRequest {
            query: String,
            freshness: String,
            summary: bool,
            count: usize,
        }

        #[derive(Deserialize, Debug)]
        struct WebPage {
            name: String,
            snippet: Option<String>,
            summary: Option<String>,
            url: String,
            #[serde(rename = "siteName")]
            site_name: Option<String>,
            #[serde(rename = "datePublished")]
            date_published: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct WebPages {
            value: Vec<WebPage>,
        }

        #[derive(Deserialize, Debug)]
        struct BochaData {
            #[serde(rename = "webPages")]
            web_pages: Option<WebPages>,
        }

        #[derive(Deserialize, Debug)]
        struct BochaResponse {
            code: u32,
            msg: Option<String>,
            data: Option<BochaData>,
        }

        let request = BochaRequest {
            query: query.to_string(),
            freshness: "oneMonth".to_string(),
            summary: true,
            count: max_results.min(50),
        };

        let response = self
            .client
            .post("https://api.bocha.cn/v1/web-search")
            .header("Authorization", format!("Bearer {}", api_key))
            .header("Content-Type", "application/json")
            .json(&request)
            .timeout(Duration::from_secs(10))
            .send()
            .await
            .context("Bocha API 请求失败")?;

        let status = response.status();
        if !status.is_success() {
            let error_text = response.text().await.unwrap_or_default();
            
            let error_msg = match status.as_u16() {
                403 => format!("余额不足: {}", error_text),
                401 => format!("API KEY无效: {}", error_text),
                400 => format!("请求参数错误: {}", error_text),
                429 => format!("请求频率达到限制: {}", error_text),
                _ => format!("HTTP {}: {}", status, error_text),
            };
            
            warn!("[Bocha] 搜索失败: {}", error_msg);
            return Ok(SearchResponse::error(
                query.to_string(),
                self.name.clone(),
                error_msg,
            ));
        }

        let bocha_response: BochaResponse = response
            .json()
            .await
            .context("解析 Bocha 响应失败")?;

        if bocha_response.code != 200 {
            let error_msg = bocha_response
                .msg
                .unwrap_or_else(|| format!("API返回错误码: {}", bocha_response.code));
            return Ok(SearchResponse::error(
                query.to_string(),
                self.name.clone(),
                error_msg,
            ));
        }

        info!("[Bocha] 搜索完成，query='{}'", query);
        debug!("[Bocha] 原始响应: {:?}", bocha_response);

        let results = bocha_response
            .data
            .and_then(|d| d.web_pages)
            .map(|wp| wp.value)
            .unwrap_or_default()
            .into_iter()
            .take(max_results)
            .map(|item| {
                let snippet = item
                    .summary
                    .or(item.snippet)
                    .unwrap_or_default()
                    .chars()
                    .take(500)
                    .collect();

                let source = item
                    .site_name
                    .unwrap_or_else(|| extract_domain(&item.url));

                let mut result = SearchResult {
                    title: item.name,
                    snippet,
                    url: item.url,
                    source,
                    published_date: item.date_published,
                    news_type: NewsType::Other,
                    sentiment: Sentiment::Unknown,
                    importance: 5,
                    relevance: 0.8, // Bocha中文搜索优化，相关度较高
                    keywords: Vec::new(),
                };
                result.analyze_type();
                result.analyze_sentiment();
                result.calculate_importance();
                result
            })
            .collect::<Vec<_>>();

        info!("[Bocha] 成功解析 {} 条结果", results.len());

        Ok(SearchResponse::success(
            query.to_string(),
            self.name.clone(),
            results,
        ))
    }
}

#[async_trait]
impl SearchProvider for BochaSearchProvider {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_available(&self) -> bool {
        let manager = self.key_manager.lock().unwrap();
        !manager.keys.is_empty()
    }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        let api_key = {
            let mut manager = self.key_manager.lock().unwrap();
            manager.get_next_key()
        };

        let api_key = match api_key {
            Some(key) => key,
            None => {
                return SearchResponse::error(
                    query.to_string(),
                    self.name.clone(),
                    "Bocha 未配置 API Key".to_string(),
                );
            }
        };

        let start_time = Instant::now();
        let mut response = match self.do_search(query, &api_key, max_results).await {
            Ok(resp) => resp,
            Err(e) => {
                let mut manager = self.key_manager.lock().unwrap();
                manager.record_error(&api_key);
                error!("[Bocha] 搜索 '{}' 失败: {}", query, e);
                SearchResponse::error(query.to_string(), self.name.clone(), e.to_string())
            }
        };

        response.search_time = start_time.elapsed().as_secs_f64();

        if response.success {
            let mut manager = self.key_manager.lock().unwrap();
            manager.record_success(&api_key);
            info!(
                "[Bocha] 搜索 '{}' 成功，返回 {} 条结果，耗时 {:.2}s",
                query,
                response.results.len(),
                response.search_time
            );
        } else {
            let mut manager = self.key_manager.lock().unwrap();
            manager.record_error(&api_key);
        }

        response
    }
}

