//! Generated by refactor stage 2 — extracted from src/search_service.rs

use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use async_trait::async_trait;
use log::{error, info};
use serde::Deserialize;

use super::super::types::{NewsType, SearchProvider, SearchResponse, SearchResult, Sentiment};


// ============================================================================
// 东方财富 新闻API
// ============================================================================

/// 东方财富新闻API
///
/// 特点：
/// - 完全免费，无需API Key
/// - A股专业财经资讯
/// - 实时公告、新闻、研报
/// - 数据权威，更新快
///
/// 接口文档：https://quote.eastmoney.com/
pub struct EastmoneyNewsProvider {
    name: String,
    client: reqwest::Client,
}

impl EastmoneyNewsProvider {
    pub fn new() -> Self {
        Self {
            name: "东方财富".to_string(),
            client: reqwest::Client::builder()
                .timeout(Duration::from_secs(10))
                .build()
                .unwrap(),
        }
    }

    async fn do_search(&self, query: &str, max_results: usize) -> Result<SearchResponse> {
        // 从查询中提取股票代码和名称
        let (_stock_code, stock_name) = Self::parse_query(query);
        
        // 东方财富支持纯关键词搜索，不强制要求股票代码
        let search_keyword = if !stock_name.is_empty() {
            stock_name
        } else {
            // 使用原始查询作为关键词（去掉"股票""最新""消息"等停用词后的部分）
            query.to_string()
        };

        if search_keyword.is_empty() {
            return Ok(SearchResponse::error(
                query.to_string(),
                self.name.clone(),
                "无法从查询中提取搜索关键词".to_string(),
            ));
        }

        let start = Instant::now();
        
        // 东方财富新闻搜索API
        // 示例: http://search-api-web.eastmoney.com/search/jsonp?cb=jQuery&param=...
        let url = format!(
            "http://search-api-web.eastmoney.com/search/jsonp?cb=jQuery&param=%7B%22uid%22%3A%22%22%2C%22keyword%22%3A%22{}%22%2C%22type%22%3A%5B%22cmsArticleWebOld%22%5D%2C%22client%22%3A%22web%22%2C%22clientType%22%3A%22web%22%2C%22clientVersion%22%3A%22curr%22%2C%22param%22%3A%7B%22cmsArticleWebOld%22%3A%7B%22searchScope%22%3A%22default%22%2C%22sort%22%3A%22default%22%2C%22pageIndex%22%3A1%2C%22pageSize%22%3A{}%7D%7D%7D",
            urlencoding::encode(&search_keyword),
            max_results
        );

        let response_text = self
            .client
            .get(&url)
            .header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36")
            .header("Referer", "http://so.eastmoney.com/")
            .send()
            .await
            .context("东方财富API请求失败")?
            .text()
            .await
            .context("读取响应失败")?;

        // 移除 JSONP 包装：jQuery(...) -> ...
        let json_text = response_text
            .trim()
            .strip_prefix("jQuery(")
            .and_then(|s| s.strip_suffix(")"))
            .unwrap_or(&response_text);

        #[derive(Deserialize, Debug)]
        struct EastmoneyArticle {
            title: String,
            content: Option<String>,
            url: String,
            date: Option<String>,
            #[serde(rename = "mediaName")]
            media_name: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct EastmoneyResult {
            #[serde(rename = "cmsArticleWebOld")]
            cms_article: Option<Vec<EastmoneyArticle>>,
        }

        #[derive(Deserialize, Debug)]
        struct EastmoneyResponse {
            code: i32,
            msg: String,
            result: Option<EastmoneyResult>,
        }

        let parsed: EastmoneyResponse = serde_json::from_str(json_text)
            .context("解析东方财富响应失败")?;

        if parsed.code != 0 {
            return Ok(SearchResponse::error(
                query.to_string(),
                self.name.clone(),
                format!("API返回错误: {}", parsed.msg),
            ));
        }

        let articles = parsed
            .result
            .and_then(|r| r.cms_article)
            .unwrap_or_default();

        info!(
            "[东方财富] 搜索完成，query='{}', 返回 {} 条结果",
            query,
            articles.len()
        );

        let results = articles
            .into_iter()
            .map(|item| {
                let source = item.media_name.unwrap_or_else(|| "东方财富".to_string());
                let snippet = item.content
                    .unwrap_or_else(|| item.title.clone())
                    .chars()
                    .take(500)
                    .collect();

                let mut result = SearchResult {
                    title: item.title,
                    snippet,
                    url: item.url,
                    source,
                    published_date: item.date,
                    news_type: NewsType::Other,
                    sentiment: Sentiment::Unknown,
                    importance: 6, // 东方财富权威性较高
                    relevance: 0.8, // A股专业平台，相关性高
                    keywords: Vec::new(),
                };
                result.analyze_type();
                result.analyze_sentiment();
                result
            })
            .collect();

        Ok(SearchResponse {
            query: query.to_string(),
            results,
            success: true,
            provider: self.name.clone(),
            error_message: None,
            search_time: start.elapsed().as_secs_f64(),
        })
    }

    /// 从查询中解析股票代码和名称/关键词
    /// 例如: "贵州茅台 600519 股票 最新消息" -> ("600519", "贵州茅台")
    /// 也支持: "金风 持股 投资 收购 参股" -> ("", "金风 持股 投资 收购 参股")
    fn parse_query(query: &str) -> (String, String) {
        let parts: Vec<&str> = query.split_whitespace().collect();
        
        let mut code = String::new();
        let mut name_parts: Vec<String> = Vec::new();
        let stop_words = ["股票", "最新", "消息", "新闻"];
        
        for part in &parts {
            // 匹配6位数字的股票代码
            if part.len() == 6 && part.chars().all(|c| c.is_ascii_digit()) {
                code = part.to_string();
            } else if !stop_words.iter().any(|w| part.contains(w)) {
                // 收集非停用词作为搜索关键词
                name_parts.push(part.to_string());
            }
        }
        
        (code, name_parts.join(" "))
    }
}

#[async_trait]
impl SearchProvider for EastmoneyNewsProvider {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_available(&self) -> bool {
        true // 东方财富API免费，始终可用
    }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        match self.do_search(query, max_results).await {
            Ok(response) => {
                info!(
                    "[东方财富] 搜索 '{}' 成功，返回 {} 条结果，耗时 {:.2}s",
                    query,
                    response.results.len(),
                    response.search_time
                );
                response
            }
            Err(e) => {
                error!("[东方财富] 搜索失败: {}", e);
                SearchResponse::error(query.to_string(), self.name.clone(), e.to_string())
            }
        }
    }
}

