//! Generated by refactor stage 2 — 东财全市场公告流 provider
//!
//! 数据源：https://np-anotice-stock.eastmoney.com/api/security/ann
//! - 按日期范围拉取全市场公告（沪深北）
//! - 完全免费，无需 API Key
//! - 含 art_code/title/notice_date/display_time/codes/columns 等结构化字段
//!
//! 特点：
//! - 覆盖 A 股 5000+ 公司每天新增公告（典型 200-500 条/日）
//! - 比手动看 cninfo/巨潮快 5-10 分钟
//! - 含 column_name 分类（高管变动/分配方案/重大合同/重组 等）
//! - 用作 ①「事件抽取」的高质量原料（公告 > 新闻 > 传闻）
//!
//! 反爬：模拟浏览器 Referer/User-Agent，无频率限制

use std::time::Duration;

use anyhow::{Context, Result};
use async_trait::async_trait;
#[cfg(test)]
use chrono::NaiveDate;
use serde::Deserialize;

use super::super::types::{SearchProvider, SearchResponse, SearchResult};

/// 东财全市场公告流 provider
pub struct EmAnnouncementProvider {
    name: String,
    client: reqwest::Client,
}

impl EmAnnouncementProvider {
    pub fn new() -> Self {
        Self {
            name: "东财公告".to_string(),
            client: reqwest::Client::builder()
                .timeout(Duration::from_secs(15))
                .user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
                .build()
                .unwrap(),
        }
    }

    /// 抓取指定日期的全市场公告
    ///
    /// - `date`: YYYY-MM-DD（通常传当天/昨天）
    /// - `limit`: 最大返回条数（API 单页最多 ~100）
    pub async fn fetch_announcements(&self, date: &str, limit: usize) -> Result<Vec<SearchResult>> {
        #[derive(Deserialize, Debug)]
        struct Code {
            short_name: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct Column {
            column_name: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct AnnItem {
            art_code: Option<String>,
            title: Option<String>,
            #[serde(default)]
            notice_date: Option<String>,
            #[serde(default)]
            display_time: Option<String>,
            #[serde(default)]
            codes: Vec<Code>,
            #[serde(default)]
            columns: Vec<Column>,
        }

        #[derive(Deserialize, Debug)]
        struct AnnData {
            list: Option<Vec<AnnItem>>,
        }

        #[derive(Deserialize, Debug)]
        struct AnnResp {
            data: Option<AnnData>,
        }

        // 不传 stock_list = 全市场；带 begin_time/end_time 限定日期
        let url = format!(
            "https://np-anotice-stock.eastmoney.com/api/security/ann?cb=jQuery&page_size={}&page_index=1&ann_type=A&client_source=web&begin_time={}&end_time={}",
            limit.min(100), date, date
        );

        let body = self
            .client
            .get(&url)
            .header("Referer", "https://data.eastmoney.com/")
            .header("Origin", "https://data.eastmoney.com")
            .send()
            .await
            .context("东财公告请求失败")?
            .text()
            .await
            .context("东财公告读取 body 失败")?;

        // 接口返回 jQuery(...) JSONP, 剥掉 jQuery(...) 包裹
        let json_str = if let Some(start) = body.find('(') {
            if let Some(end) = body.rfind(')') {
                &body[start + 1..end]
            } else {
                &body
            }
        } else {
            &body
        };

        let resp: AnnResp = serde_json::from_str(json_str).with_context(|| {
            format!(
                "东财公告 JSON 解析失败: head={}",
                &body.chars().take(120).collect::<String>()
            )
        })?;

        let items = resp.data.and_then(|d| d.list).unwrap_or_default();
        let mut results: Vec<SearchResult> = Vec::new();
        for item in items {
            let title = match item.title.filter(|t| !t.is_empty()) {
                Some(t) => t,
                None => continue,
            };

            // 标题增强：附加 stock_code + column_name（提高下游分类准确率）
            let stock_tag = item
                .codes
                .first()
                .and_then(|c| c.short_name.clone())
                .map(|n| format!("[{}] ", n))
                .unwrap_or_default();
            let col_tag = item
                .columns
                .first()
                .and_then(|c| c.column_name.clone())
                .map(|n| format!("({}) ", n))
                .unwrap_or_default();
            let enriched_title = format!("{}{}{}", stock_tag, col_tag, title);

            let art_code = item.art_code.unwrap_or_default();
            let url = if art_code.is_empty() {
                "https://data.eastmoney.com/notice/".to_string()
            } else {
                format!("https://data.eastmoney.com/notice/detail/{}", art_code)
            };

            // 显示日期：notice_date 或 display_time HH:MM
            let date_tag = item
                .notice_date
                .clone()
                .or_else(|| item.display_time.clone())
                .unwrap_or_default();

            results.push(
                SearchResult::new(
                    enriched_title.chars().take(120).collect(),
                    title.chars().take(240).collect(),
                    url,
                    "东财公告".to_string(),
                )
                .with_date(date_tag),
            );
            if results.len() >= limit {
                break;
            }
        }
        Ok(results)
    }

    /// 抓取今日公告（快捷方法）
    pub async fn fetch_today(&self, limit: usize) -> Result<Vec<SearchResult>> {
        let today = chrono::Local::now().format("%Y-%m-%d").to_string();
        self.fetch_announcements(&today, limit).await
    }

    /// 抓取昨天公告（盘后场景：补抓昨日全部公告）
    pub async fn fetch_yesterday(&self, limit: usize) -> Result<Vec<SearchResult>> {
        let yesterday = (chrono::Local::now() - chrono::Duration::days(1))
            .format("%Y-%m-%d")
            .to_string();
        self.fetch_announcements(&yesterday, limit).await
    }

    /// 抓取某个具体 A 股的最近公告
    pub async fn fetch_by_stock(
        &self,
        stock_code: &str,
        limit: usize,
    ) -> Result<Vec<SearchResult>> {
        #[derive(Deserialize, Debug)]
        struct AnnItem {
            art_code: Option<String>,
            title: Option<String>,
            #[serde(default)]
            notice_date: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct AnnData {
            list: Option<Vec<AnnItem>>,
        }

        #[derive(Deserialize, Debug)]
        struct AnnResp {
            data: Option<AnnData>,
        }

        let url = format!(
            "https://np-anotice-stock.eastmoney.com/api/security/ann?cb=jQuery&page_size={}&page_index=1&ann_type=A&client_source=web&stock_list={}",
            limit.min(50), stock_code
        );

        let body = self
            .client
            .get(&url)
            .header("Referer", "https://data.eastmoney.com/")
            .send()
            .await
            .context("东财个股公告请求失败")?
            .text()
            .await
            .context("东财个股公告读取失败")?;

        let json_str = if let Some(start) = body.find('(') {
            if let Some(end) = body.rfind(')') {
                &body[start + 1..end]
            } else {
                &body
            }
        } else {
            &body
        };

        let resp: AnnResp = serde_json::from_str(json_str).with_context(|| {
            format!(
                "东财个股公告解析失败: head={}",
                &body.chars().take(120).collect::<String>()
            )
        })?;

        let items = resp.data.and_then(|d| d.list).unwrap_or_default();
        let mut results: Vec<SearchResult> = Vec::new();
        for item in items {
            let title = match item.title.filter(|t| !t.is_empty()) {
                Some(t) => t,
                None => continue,
            };
            let art_code = item.art_code.unwrap_or_default();
            let url = format!("https://data.eastmoney.com/notice/detail/{}", art_code);
            let date_tag = item.notice_date.unwrap_or_default();
            results.push(
                SearchResult::new(
                    title.chars().take(120).collect(),
                    title.chars().take(240).collect(),
                    url,
                    "东财公告".to_string(),
                )
                .with_date(date_tag),
            );
            if results.len() >= limit {
                break;
            }
        }
        Ok(results)
    }

    /// 校验日期格式 YYYY-MM-DD
    #[cfg(test)]
    fn valid_date(s: &str) -> bool {
        NaiveDate::parse_from_str(s, "%Y-%m-%d").is_ok()
    }
}

#[async_trait]
impl SearchProvider for EmAnnouncementProvider {
    fn name(&self) -> &str {
        &self.name
    }
    fn is_available(&self) -> bool {
        true
    }

    /// 调用 fetch_today(50)，作为 SearchProvider 兜底接口
    async fn search(&self, _query: &str, max_results: usize) -> SearchResponse {
        let started = std::time::Instant::now();
        let items = self
            .fetch_today(max_results.min(50))
            .await
            .unwrap_or_default();
        SearchResponse {
            query: _query.to_string(),
            success: true,
            error_message: None,
            search_time: started.elapsed().as_secs_f64(),
            results: items,
            provider: self.name.clone(),
        }
    }
}

impl Default for EmAnnouncementProvider {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_valid_date_format() {
        assert!(EmAnnouncementProvider::valid_date("2026-06-29"));
        assert!(EmAnnouncementProvider::valid_date("2025-01-01"));
        assert!(!EmAnnouncementProvider::valid_date("2026/06/29"));
        assert!(!EmAnnouncementProvider::valid_date("29-06-2026"));
        assert!(!EmAnnouncementProvider::valid_date(""));
    }

    #[test]
    fn test_search_provider_trait_name() {
        let p = EmAnnouncementProvider::new();
        assert_eq!(p.name(), "东财公告");
        assert!(p.is_available());
    }

    #[test]
    fn test_jsonp_unwrap_basic() {
        // 验证 JSONP 包裹剥离逻辑
        let body = r#"jQuery({"data":{"list":[]}})"#;
        let start = body.find('(').unwrap();
        let end = body.rfind(')').unwrap();
        let json_str = &body[start + 1..end];
        let parsed: serde_json::Value = serde_json::from_str(json_str).unwrap();
        assert_eq!(parsed["data"]["list"][0], serde_json::Value::Null);
    }

    #[test]
    fn test_jsonp_unwrap_no_wrapper() {
        // 纯 JSON 也能处理
        let body = r#"{"data":{"list":[]}}"#;
        let json_str = if let Some(start) = body.find('(') {
            if let Some(end) = body.rfind(')') {
                &body[start + 1..end]
            } else {
                body
            }
        } else {
            body
        };
        let parsed: serde_json::Value = serde_json::from_str(json_str).unwrap();
        assert!(parsed["data"]["list"].is_array());
    }
}
