//! Generated by refactor stage 2 — extracted from src/search_service.rs

use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use super::super::types::{SearchProvider, SearchResponse, SearchResult};


// ============================================================================
// 金十数据 直连API（快讯 + 财经日历，免费无需Key）
// ============================================================================

/// 金十财经日历单条事件
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Jin10CalendarEvent {
    /// 事件本地时间（HH:MM 或 全天 / 待定）
    pub time: String,
    /// 事件日期 YYYY-MM-DD
    pub date: String,
    /// 国家 / 地区
    pub country: String,
    /// 指标 / 事件名称
    pub name: String,
    /// 重要性 1-3
    pub star: u8,
    /// 事件分类：data=经济数据，event=事件（央行/讲话等）
    pub kind: String,
    /// 前值
    pub previous: Option<String>,
    /// 预期
    pub forecast: Option<String>,
    /// 公布值
    pub actual: Option<String>,
}

/// 金十数据：财经快讯 + 财经日历
///
/// 特点：
/// - 完全免费，无需 API Key（仅需模拟浏览器头）
/// - 快讯覆盖国内外财经、央行、地缘政治，分钟级更新
/// - 财经日历包含 NFP / CPI / FOMC / PMI 等重要经济数据事件
pub struct Jin10Provider {
    name: String,
    client: reqwest::Client,
}

impl Jin10Provider {
    pub fn new() -> Self {
        Self {
            name: "金十数据".to_string(),
            client: reqwest::Client::builder()
                .timeout(Duration::from_secs(10))
                .user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
                .build()
                .unwrap(),
        }
    }

    /// 构造带金十通用请求头的 GET
    fn flash_req(&self, url: &str) -> reqwest::RequestBuilder {
        self.client.get(url)
            .header("x-app-id", "bVBF4FyRTn5NJF5n")
            .header("x-version", "1.0.0")
            .header("Referer", "https://www.jin10.com/")
            .header("Origin", "https://www.jin10.com")
    }

    /// 抓取最新快讯（过滤近 6 小时、非广告）
    ///
    /// - `limit`: 最大返回条数
    /// - `only_important`: 只返回 important=1 的标星快讯
    pub async fn fetch_flash_news(&self, limit: usize, only_important: bool) -> Result<Vec<SearchResult>> {
        #[derive(Deserialize, Debug)]
        struct FlashInner {
            #[serde(default)]
            content: Option<String>,
            #[serde(default)]
            title: Option<String>,
            #[serde(default)]
            source_link: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        #[allow(dead_code)]
        struct FlashItem {
            #[serde(default)]
            id: Option<String>,
            #[serde(default)]
            time: Option<String>,
            #[serde(default)]
            #[serde(rename = "type")]
            kind: Option<i64>,
            #[serde(default)]
            important: Option<i64>,
            #[serde(default)]
            data: Option<FlashInner>,
        }

        #[derive(Deserialize, Debug)]
        struct FlashResp {
            #[serde(default)]
            status: Option<i64>,
            #[serde(default)]
            data: Option<Vec<FlashItem>>,
        }

        let url = "https://flash-api.jin10.com/get_flash_list?channel=-8200&vip=1";
        let resp: FlashResp = self.flash_req(url)
            .send().await
            .context("金十快讯请求失败")?
            .json().await
            .context("金十快讯解析失败")?;

        if resp.status != Some(200) {
            return Err(anyhow::anyhow!("金十快讯API返回异常: {:?}", resp.status));
        }

        let now = chrono::Local::now();
        let items = resp.data.unwrap_or_default();

        let mut results: Vec<SearchResult> = Vec::new();
        for item in items {
            // type=0 普通快讯，type=1 数据类，其他可能是广告/图片，跳过
            let kind = item.kind.unwrap_or(0);
            if kind > 1 { continue; }

            let inner = match item.data { Some(v) => v, None => continue };
            let content = inner.content.unwrap_or_default();
            if content.is_empty() { continue; }

            let important_flag = item.important.unwrap_or(0) == 1;
            if only_important && !important_flag { continue; }

            // 解析时间，过滤 6h 以外
            let (date_tag, ts_opt) = match item.time.as_deref() {
                Some(t) => {
                    let parsed = chrono::NaiveDateTime::parse_from_str(t, "%Y-%m-%d %H:%M:%S")
                        .ok()
                        .and_then(|ndt| ndt.and_local_timezone(chrono::Local).single());
                    match parsed {
                        Some(dt) => (dt.format("%H:%M").to_string(), Some(dt.timestamp())),
                        None => (t.to_string(), None),
                    }
                }
                None => (String::new(), None),
            };
            if let Some(ts) = ts_opt {
                if now.timestamp() - ts > 6 * 3600 { continue; }
            }

            // 截取标题
            let title = inner.title.filter(|s| !s.is_empty()).unwrap_or_else(|| {
                content.chars().take(60).collect()
            });
            let snippet: String = content.chars().take(240).collect();
            let title_display = if important_flag {
                format!("⭐ {}", title)
            } else {
                title
            };
            let url = inner.source_link.filter(|s| !s.is_empty())
                .unwrap_or_else(|| "https://www.jin10.com/".to_string());

            results.push(
                SearchResult::new(title_display, snippet, url, "金十数据".to_string())
                    .with_date(date_tag)
            );
            if results.len() >= limit { break; }
        }

        Ok(results)
    }

    /// 抓取财经日历（未来 `days_ahead` 天内重要经济数据/事件）
    ///
    /// 数据源：`https://cdn-rili.jin10.com/web_data/{year}/week/{week}/economics.json`
    /// 以及对应的 `event.json`（央行讲话/非数据事件）
    ///
    /// - `days_ahead`: 0=仅今天，1=今天+明天，N=未来 N+1 天
    /// - `min_star`: 只保留重要性 >= min_star 的事件（1-3）
    pub async fn fetch_calendar(&self, days_ahead: u32, min_star: u8) -> Result<Vec<Jin10CalendarEvent>> {
        use chrono::Datelike;
        let today = chrono::Local::now().date_naive();
        let mut weeks: std::collections::BTreeSet<(i32, u32)> = std::collections::BTreeSet::new();
        for d in 0..=days_ahead {
            let day = today + chrono::Duration::days(d as i64);
            weeks.insert((day.iso_week().year(), day.iso_week().week()));
        }

        let mut events: Vec<Jin10CalendarEvent> = Vec::new();
        let min_date = today;
        let max_date = today + chrono::Duration::days(days_ahead as i64);

        for (year, week) in weeks {
            // 抓经济数据 & 事件（并发）
            let econ_url = format!("https://cdn-rili.jin10.com/web_data/{}/week/{:02}/economics.json", year, week);
            let event_url = format!("https://cdn-rili.jin10.com/web_data/{}/week/{:02}/event.json", year, week);
            let (econ_res, event_res) = tokio::join!(
                self.fetch_calendar_entries(&econ_url, "data"),
                self.fetch_calendar_entries(&event_url, "event"),
            );
            if let Ok(mut v) = econ_res { events.append(&mut v); }
            if let Ok(mut v) = event_res { events.append(&mut v); }
        }

        // 过滤日期窗口 + 重要性
        events.retain(|e| {
            let in_range = chrono::NaiveDate::parse_from_str(&e.date, "%Y-%m-%d")
                .map(|d| d >= min_date && d <= max_date)
                .unwrap_or(false);
            in_range && e.star >= min_star
        });

        // 按日期 + 时间排序
        events.sort_by(|a, b| a.date.cmp(&b.date).then(a.time.cmp(&b.time)));
        Ok(events)
    }

    /// 内部：拉取单个 economics.json / event.json 并映射为统一结构
    async fn fetch_calendar_entries(&self, url: &str, kind: &str) -> Result<Vec<Jin10CalendarEvent>> {
        // 日历 CDN 不要求 app-id，但加上不会出错
        let text = self.flash_req(url).send().await
            .with_context(|| format!("金十日历请求失败: {}", url))?
            .text().await
            .context("金十日历读取失败")?;
        if text.trim().is_empty() {
            return Ok(Vec::new());
        }

        // 结构因 kind 而略有不同，统一用 serde_json::Value 解析
        let v: serde_json::Value = match serde_json::from_str(&text) {
            Ok(v) => v,
            Err(_) => return Ok(Vec::new()),
        };

        let arr = v.as_array()
            .or_else(|| v.get("data").and_then(|d| d.as_array()))
            .cloned()
            .unwrap_or_default();

        let mut out: Vec<Jin10CalendarEvent> = Vec::new();
        for item in arr {
            let date = item.get("pub_time").or_else(|| item.get("date"))
                .and_then(|s| s.as_str())
                .map(|s| s.split(' ').next().unwrap_or(s).to_string())
                .unwrap_or_default();
            if date.is_empty() { continue; }

            let time = item.get("pub_time").or_else(|| item.get("time"))
                .and_then(|s| s.as_str())
                .map(|s| {
                    let parts: Vec<&str> = s.splitn(2, ' ').collect();
                    if parts.len() == 2 { parts[1].to_string() } else { "全天".to_string() }
                })
                .unwrap_or_else(|| "全天".to_string());

            let country = item.get("country").and_then(|s| s.as_str()).unwrap_or("").to_string();
            let name = item.get("name").or_else(|| item.get("title"))
                .and_then(|s| s.as_str()).unwrap_or("").to_string();
            if name.is_empty() { continue; }

            let star = item.get("star").and_then(|s| s.as_u64()).unwrap_or(0) as u8;

            let grab_str = |key: &str| -> Option<String> {
                item.get(key).and_then(|x| {
                    if x.is_string() { x.as_str().map(|s| s.to_string()) }
                    else if x.is_number() { Some(x.to_string()) }
                    else { None }
                }).filter(|s| !s.is_empty() && s != "--")
            };

            out.push(Jin10CalendarEvent {
                time,
                date,
                country,
                name,
                star,
                kind: kind.to_string(),
                previous: grab_str("previous"),
                forecast: grab_str("consensus").or_else(|| grab_str("forecast")),
                actual: grab_str("actual"),
            });
        }
        Ok(out)
    }
}

#[async_trait]
impl SearchProvider for Jin10Provider {
    fn name(&self) -> &str { &self.name }
    fn is_available(&self) -> bool { true }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        let start = Instant::now();
        let keywords: Vec<String> = query.split_whitespace()
            .filter(|w| w.chars().count() >= 2)
            .take(6)
            .map(|w| w.to_lowercase())
            .collect();

        let flash_res = self.fetch_flash_news(60, false).await;
        let all = flash_res.unwrap_or_default();

        let filtered: Vec<SearchResult> = if keywords.is_empty() {
            all.into_iter().take(max_results).collect()
        } else {
            all.into_iter()
                .filter(|r| {
                    let text = format!("{} {}", r.title, r.snippet).to_lowercase();
                    keywords.iter().any(|kw| text.contains(kw))
                })
                .take(max_results)
                .collect()
        };

        let success = !filtered.is_empty();
        SearchResponse {
            query: query.to_string(),
            results: filtered,
            provider: self.name.clone(),
            success,
            error_message: if success { None } else { Some("金十无相关快讯".to_string()) },
            search_time: start.elapsed().as_secs_f64(),
        }
    }
}

