//! Generated by refactor stage 2 — extracted from src/search_service.rs

use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use async_trait::async_trait;
use log::{debug, error, info};
use serde::Deserialize;

use super::super::types::{extract_domain, ApiKeyManager, NewsType, SearchProvider, SearchResponse, SearchResult, Sentiment};


// ============================================================================
// SerpAPI 搜索引擎
// ============================================================================

/// SerpAPI 搜索引擎
///
/// 特点：
/// - 支持 Google、Bing、百度等多种搜索引擎
/// - 免费版每月 100 次请求
/// - 返回真实的搜索结果
///
/// 文档：https://serpapi.com/
pub struct SerpAPISearchProvider {
    name: String,
    key_manager: Arc<Mutex<ApiKeyManager>>,
    client: reqwest::Client,
}

impl SerpAPISearchProvider {
    pub fn new(api_keys: Vec<String>) -> Self {
        Self {
            name: "SerpAPI".to_string(),
            key_manager: Arc::new(Mutex::new(ApiKeyManager::new(api_keys))),
            client: reqwest::Client::new(),
        }
    }

    async fn do_search(&self, query: &str, api_key: &str, max_results: usize) -> Result<SearchResponse> {
        #[derive(Deserialize, Debug)]
        struct OrganicResult {
            title: String,
            snippet: Option<String>,
            link: String,
            source: Option<String>,
            date: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct SerpAPIResponse {
            organic_results: Option<Vec<OrganicResult>>,
        }

        let response = self
            .client
            .get("https://serpapi.com/search")
            .query(&[
                ("engine", "baidu"),
                ("q", query),
                ("api_key", api_key),
            ])
            .timeout(Duration::from_secs(10))
            .send()
            .await
            .context("SerpAPI 请求失败")?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            return Ok(SearchResponse::error(
                query.to_string(),
                self.name.clone(),
                format!("HTTP {}: {}", status, error_text),
            ));
        }

        let serp_response: SerpAPIResponse = response.json().await.context("解析 SerpAPI 响应失败")?;

        debug!("[SerpAPI] 原始响应: {:?}", serp_response);

        let organic_results = serp_response.organic_results.unwrap_or_default();
        let results = organic_results
            .into_iter()
            .take(max_results)
            .map(|item| {
                let source = item
                    .source
                    .clone()
                    .unwrap_or_else(|| extract_domain(&item.link));
                let mut result = SearchResult {
                    title: item.title,
                    snippet: item.snippet.unwrap_or_default().chars().take(500).collect(),
                    url: item.link,
                    source,
                    published_date: item.date,
                    news_type: NewsType::Other,
                    sentiment: Sentiment::Unknown,
                    importance: 5,
                    relevance: 0.7, // SerpAPI默认相关度较高
                    keywords: Vec::new(),
                };
                result.analyze_type();
                result.analyze_sentiment();
                result.calculate_importance();
                result
            })
            .collect();

        Ok(SearchResponse::success(
            query.to_string(),
            self.name.clone(),
            results,
        ))
    }
}

#[async_trait]
impl SearchProvider for SerpAPISearchProvider {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_available(&self) -> bool {
        let manager = self.key_manager.lock().unwrap();
        !manager.keys.is_empty()
    }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        let api_key = {
            let mut manager = self.key_manager.lock().unwrap();
            manager.get_next_key()
        };

        let api_key = match api_key {
            Some(key) => key,
            None => {
                return SearchResponse::error(
                    query.to_string(),
                    self.name.clone(),
                    "SerpAPI 未配置 API Key".to_string(),
                );
            }
        };

        let start_time = Instant::now();
        let mut response = match self.do_search(query, &api_key, max_results).await {
            Ok(resp) => resp,
            Err(e) => {
                let mut manager = self.key_manager.lock().unwrap();
                manager.record_error(&api_key);
                error!("[SerpAPI] 搜索 '{}' 失败: {}", query, e);
                SearchResponse::error(query.to_string(), self.name.clone(), e.to_string())
            }
        };

        response.search_time = start_time.elapsed().as_secs_f64();

        if response.success {
            let mut manager = self.key_manager.lock().unwrap();
            manager.record_success(&api_key);
            info!(
                "[SerpAPI] 搜索 '{}' 成功，返回 {} 条结果，耗时 {:.2}s",
                query,
                response.results.len(),
                response.search_time
            );
        } else {
            let mut manager = self.key_manager.lock().unwrap();
            manager.record_error(&api_key);
        }

        response
    }
}

