//! Generated by refactor stage 2 — 新浪财经全球快讯 provider
//!
//! BR-036: 主题池能力位过滤配套源（快讯源保留在 fetch_flash_titles）。
//! 数据源：https://feed.mix.sina.com.cn/api/roll/get
//! - lid=1686 国际财经
//! - lid=2516 国内财经
//! - lid=2509 股市动态
//! - lid=1687 港股
//!
//! 特点：
//! - 完全免费，无需 API Key
//! - 7×24 滚动，覆盖国内外宏观/股市/A股/港股
//! - 与财联社/金十互为冗余，新浪在国际新闻上更快

use std::time::Duration;

use anyhow::{Context, Result};
use async_trait::async_trait;
use log::debug;
use serde::Deserialize;

use super::super::types::{SearchProvider, SearchResponse, SearchResult};

/// 新浪财经全球快讯 provider
pub struct SinaFlashProvider {
    name: String,
    client: reqwest::Client,
    /// 多个 lid 并发拉取，覆盖不同主题（国际/国内/A股/港股）
    lids: Vec<u32>,
}

impl SinaFlashProvider {
    pub fn new() -> Self {
        Self::with_lids(vec![1686, 2516, 2509, 1687])
    }

    /// 自定义 lids 的构造（测试或单 lid 部署用）
    pub fn with_lids(lids: Vec<u32>) -> Self {
        Self {
            name: "新浪财经".to_string(),
            client: reqwest::Client::builder()
                .timeout(Duration::from_secs(10))
                .user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
                .build()
                .unwrap(),
            lids,
        }
    }

    /// 拉取单 lid 的快讯列表
    async fn fetch_lid(&self, lid: u32, limit: usize) -> Result<Vec<SearchResult>> {
        #[derive(Deserialize, Debug)]
        struct Item {
            title: Option<String>,
            url: Option<String>,
            intro: Option<String>,
            ctime: Option<i64>,
        }

        #[derive(Deserialize, Debug)]
        struct Resp {
            result: Option<RespResult>,
        }

        #[derive(Deserialize, Debug)]
        struct RespResult {
            data: Option<Vec<Item>>,
        }

        let url = format!(
            "https://feed.mix.sina.com.cn/api/roll/get?pageid=153&lid={}&num={}&versionNumber=1.2.4&page=1&encode=utf-8",
            lid, limit
        );

        let resp: Resp = self
            .client
            .get(&url)
            .header("Referer", "https://finance.sina.com.cn/")
            .header("Origin", "https://finance.sina.com.cn")
            .send()
            .await
            .with_context(|| format!("新浪快讯 lid={} 请求失败", lid))?
            .json()
            .await
            .with_context(|| format!("新浪快讯 lid={} 解析失败", lid))?;

        let data = match resp.result.and_then(|r| r.data) {
            Some(d) => d,
            None => return Ok(Vec::new()),
        };

        let now = chrono::Local::now().timestamp();
        let mut results: Vec<SearchResult> = Vec::new();
        for item in data {
            let title = match item.title.filter(|t| !t.is_empty()) {
                Some(t) => t,
                None => continue,
            };
            // 过滤 6 小时以外的旧新闻
            if let Some(ts) = item.ctime {
                if now - ts > 6 * 3600 {
                    continue;
                }
            }
            let date_tag = item.ctime.map(|ts| {
                chrono::DateTime::from_timestamp(ts, 0)
                    .map(|dt| dt.with_timezone(&chrono::Local).format("%H:%M").to_string())
                    .unwrap_or_default()
            });
            let snippet = item
                .intro
                .filter(|s| !s.is_empty())
                .unwrap_or_else(|| title.chars().take(140).collect());
            let url = item
                .url
                .filter(|u| !u.is_empty())
                .unwrap_or_else(|| "https://finance.sina.com.cn/".to_string());

            results.push(
                SearchResult::new(
                    title.chars().take(80).collect(),
                    snippet.chars().take(240).collect(),
                    url,
                    format!("新浪财经({})", lid),
                )
                .with_date(date_tag.unwrap_or_default()),
            );
            if results.len() >= limit {
                break;
            }
        }
        Ok(results)
    }

    /// 抓取所有 lid 的快讯并合并去重（按 title 前 30 字）
    pub async fn fetch_flash_news(&self, limit_per_lid: usize) -> Vec<SearchResult> {
        let responses = futures::future::join_all(
            self.lids
                .iter()
                .map(|lid| self.fetch_lid(*lid, limit_per_lid)),
        )
        .await;

        let mut all: Vec<SearchResult> = Vec::new();
        for res in responses {
            match res {
                Ok(v) => all.extend(v),
                Err(e) => debug!("[sina_flash] lid 拉取失败: {}", e),
            }
        }

        // 按 title 前 30 字去重
        let mut seen = std::collections::HashSet::new();
        all.retain(|r| {
            let key: String = r.title.chars().take(30).collect();
            seen.insert(key)
        });
        all
    }
}

#[async_trait]
impl SearchProvider for SinaFlashProvider {
    fn name(&self) -> &str {
        &self.name
    }
    fn is_available(&self) -> bool {
        true
    }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        let started = std::time::Instant::now();
        let items = self.fetch_flash_news(max_results.min(50)).await;
        SearchResponse {
            query: query.to_string(),
            success: true,
            error_message: None,
            search_time: started.elapsed().as_secs_f64(),
            results: items,
            provider: self.name.clone(),
        }
    }
}

impl Default for SinaFlashProvider {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_lids() {
        let p = SinaFlashProvider::new();
        assert_eq!(p.lids, vec![1686, 2516, 2509, 1687]);
        assert!(p.is_available());
    }

    #[test]
    fn test_with_custom_lids() {
        let p = SinaFlashProvider::with_lids(vec![1686]);
        assert_eq!(p.lids, vec![1686]);
    }

    #[tokio::test]
    async fn test_fetch_lid_dedup() {
        // 模拟 fetch_lid 返回重复 (title 前缀相同), 验证去重逻辑
        let _p = SinaFlashProvider::with_lids(vec![]);
        let items = vec![
            SearchResult::new(
                "工信部: 5G-A 商用".into(),
                "".into(),
                "u".into(),
                "新浪".into(),
            ),
            SearchResult::new(
                "工信部: 5G-A 商用正式启动".into(),
                "".into(),
                "u".into(),
                "新浪".into(),
            ),
            SearchResult::new("央行加息 25bp".into(), "".into(), "u".into(), "新浪".into()),
        ];
        // 用 dedup 逻辑验证
        let mut seen = std::collections::HashSet::new();
        let mut deduped = Vec::new();
        for r in items {
            let key: String = r.title.chars().take(10).collect();
            if seen.insert(key) {
                deduped.push(r);
            }
        }
        assert_eq!(deduped.len(), 2, "前两条 title 前 10 字相同, 应去重");
    }

    #[test]
    fn test_search_provider_trait_name() {
        let p = SinaFlashProvider::new();
        assert_eq!(p.name(), "新浪财经");
    }
}
