//! Generated by refactor stage 2 — extracted from src/search_service.rs

use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use async_trait::async_trait;
use log::{debug, error, info};
use serde::{Deserialize, Serialize};

use super::super::types::{extract_domain, ApiKeyManager, NewsType, SearchProvider, SearchResponse, SearchResult, Sentiment};


// ============================================================================
// Tavily 搜索引擎
// ============================================================================

/// Tavily 搜索引擎
///
/// 特点：
/// - 专为 AI/LLM 优化的搜索 API
/// - 免费版每月 1000 次请求
/// - 返回结构化的搜索结果
///
/// 文档：https://docs.tavily.com/
pub struct TavilySearchProvider {
    name: String,
    key_manager: Arc<Mutex<ApiKeyManager>>,
    client: reqwest::Client,
}

impl TavilySearchProvider {
    pub fn new(api_keys: Vec<String>) -> Self {
        Self {
            name: "Tavily".to_string(),
            key_manager: Arc::new(Mutex::new(ApiKeyManager::new(api_keys))),
            client: reqwest::Client::new(),
        }
    }

    async fn do_search(&self, query: &str, api_key: &str, max_results: usize) -> Result<SearchResponse> {
        #[derive(Serialize)]
        struct TavilyRequest {
            query: String,
            search_depth: String,
            max_results: usize,
            include_answer: bool,
            include_raw_content: bool,
            days: u32,
        }

        #[derive(Deserialize, Debug)]
        struct TavilyResult {
            title: String,
            content: String,
            url: String,
            published_date: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct TavilyResponse {
            results: Vec<TavilyResult>,
        }

        let request = TavilyRequest {
            query: query.to_string(),
            search_depth: "advanced".to_string(),
            max_results,
            include_answer: false,
            include_raw_content: false,
            days: 7,
        };

        let response = self
            .client
            .post("https://api.tavily.com/search")
            .header("Content-Type", "application/json")
            .json(&request)
            .bearer_auth(api_key)
            .timeout(Duration::from_secs(10))
            .send()
            .await
            .context("Tavily API 请求失败")?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            
            let error_msg = if status.as_u16() == 429 || error_text.to_lowercase().contains("rate limit") {
                format!("API 配额已用尽: {}", error_text)
            } else {
                format!("HTTP {}: {}", status, error_text)
            };
            
            return Ok(SearchResponse::error(
                query.to_string(),
                self.name.clone(),
                error_msg,
            ));
        }

        let tavily_response: TavilyResponse = response.json().await.context("解析 Tavily 响应失败")?;

        info!(
            "[Tavily] 搜索完成，query='{}', 返回 {} 条结果",
            query,
            tavily_response.results.len()
        );
        debug!("[Tavily] 原始响应: {:?}", tavily_response);

        let results = tavily_response
            .results
            .into_iter()
            .map(|item| {
                let source = extract_domain(&item.url);
                let mut result = SearchResult {
                    title: item.title,
                    snippet: item.content.chars().take(500).collect(),
                    url: item.url.clone(),
                    source,
                    published_date: item.published_date,
                    news_type: NewsType::Other,
                    sentiment: Sentiment::Unknown,
                    importance: 5,
                    relevance: 0.6, // Tavily默认相关度
                    keywords: Vec::new(),
                };
                result.analyze_type();
                result.analyze_sentiment();
                result.calculate_importance();
                result
            })
            .collect();

        Ok(SearchResponse::success(
            query.to_string(),
            self.name.clone(),
            results,
        ))
    }
}

#[async_trait]
impl SearchProvider for TavilySearchProvider {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_available(&self) -> bool {
        let manager = self.key_manager.lock().unwrap();
        !manager.keys.is_empty()
    }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        let api_key = {
            let mut manager = self.key_manager.lock().unwrap();
            manager.get_next_key()
        };

        let api_key = match api_key {
            Some(key) => key,
            None => {
                return SearchResponse::error(
                    query.to_string(),
                    self.name.clone(),
                    "Tavily 未配置 API Key".to_string(),
                );
            }
        };

        let start_time = Instant::now();
        let mut response = match self.do_search(query, &api_key, max_results).await {
            Ok(resp) => resp,
            Err(e) => {
                let mut manager = self.key_manager.lock().unwrap();
                manager.record_error(&api_key);
                error!("[Tavily] 搜索 '{}' 失败: {}", query, e);
                SearchResponse::error(query.to_string(), self.name.clone(), e.to_string())
            }
        };

        response.search_time = start_time.elapsed().as_secs_f64();

        if response.success {
            let mut manager = self.key_manager.lock().unwrap();
            manager.record_success(&api_key);
            info!(
                "[Tavily] 搜索 '{}' 成功，返回 {} 条结果，耗时 {:.2}s",
                query,
                response.results.len(),
                response.search_time
            );
        } else {
            let mut manager = self.key_manager.lock().unwrap();
            manager.record_error(&api_key);
        }

        response
    }
}

