//! Generated by refactor stage 2 — extracted from src/search_service.rs

use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use async_trait::async_trait;
use serde::Deserialize;

use super::super::types::{SearchProvider, SearchResponse, SearchResult};


// ============================================================================
// 华尔街见闻 直连API
// ============================================================================

/// 华尔街见闻 快讯/文章直连抓取
///
/// 特点：
/// - 完全免费，无需 API Key
/// - 覆盖全球财经资讯、美联储、高盛研报、地缘政治等
/// - 快讯更新及时（分钟级）
pub struct WallStreetCnProvider {
    name: String,
    client: reqwest::Client,
}

impl WallStreetCnProvider {
    pub fn new() -> Self {
        Self {
            name: "华尔街见闻".to_string(),
            client: reqwest::Client::builder()
                .timeout(Duration::from_secs(10))
                .user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
                .build()
                .unwrap(),
        }
    }

    /// 获取最新快讯（全球财经）
    pub async fn fetch_live_news(&self, page_size: usize) -> Result<Vec<SearchResult>> {
        #[derive(Deserialize, Debug)]
        struct LiveItem {
            content_text: Option<String>,
            created_at: Option<i64>,
        }

        #[derive(Deserialize, Debug)]
        struct LiveData {
            items: Option<Vec<LiveItem>>,
        }

        #[derive(Deserialize, Debug)]
        struct LiveResp {
            code: Option<i64>,
            data: Option<LiveData>,
        }

        let url = format!(
            "https://api.wallstreetcn.com/apiv1/content/lives?channel=global-channel&cursor=0&pageSize={}&accept=0",
            page_size
        );

        let resp: LiveResp = self.client
            .get(&url)
            .header("Origin", "https://wallstreetcn.com")
            .header("Referer", "https://wallstreetcn.com/")
            .send().await
            .context("华尔街见闻快讯请求失败")?
            .json().await
            .context("华尔街见闻快讯解析失败")?;

        if resp.code != Some(20000) {
            return Err(anyhow::anyhow!("华尔街见闻API返回错误码: {:?}", resp.code));
        }

        let items = resp.data.and_then(|d| d.items).unwrap_or_default();
        let now = chrono::Local::now().timestamp();

        let results: Vec<SearchResult> = items.into_iter()
            .filter_map(|item| {
                let text = item.content_text.filter(|t| !t.is_empty())?;
                // 过滤6小时以外的旧新闻
                if let Some(ts) = item.created_at {
                    if now - ts > 6 * 3600 {
                        return None;
                    }
                }
                let date_tag = item.created_at.map(|ts| {
                    let dt = chrono::DateTime::from_timestamp(ts, 0)
                        .unwrap_or_default()
                        .with_timezone(&chrono::Local);
                    dt.format("%H:%M").to_string()
                });
                let title: String = text.chars().take(60).collect();
                let snippet: String = text.chars().take(200).collect();
                Some(SearchResult::new(
                    title,
                    snippet,
                    format!("https://wallstreetcn.com/"),
                    "华尔街见闻".to_string(),
                ).with_date(date_tag.unwrap_or_default()))
            })
            .collect();

        Ok(results)
    }

    /// 获取最新文章（深度分析）
    pub async fn fetch_articles(&self, page_size: usize) -> Result<Vec<SearchResult>> {
        #[derive(Deserialize, Debug)]
        struct ArticleItem {
            title: Option<String>,
            summary: Option<String>,
            display_time: Option<i64>,
            content_uri: Option<String>,
        }

        #[derive(Deserialize, Debug)]
        struct ArticleData {
            items: Option<Vec<ArticleItem>>,
        }

        #[derive(Deserialize, Debug)]
        struct ArticleResp {
            code: Option<i64>,
            data: Option<ArticleData>,
        }

        let url = format!(
            "https://api.wallstreetcn.com/apiv1/content/articles?channel=global-channel&accept=article&cursor=0&pageSize={}",
            page_size
        );

        let resp: ArticleResp = self.client
            .get(&url)
            .header("Origin", "https://wallstreetcn.com")
            .header("Referer", "https://wallstreetcn.com/")
            .send().await
            .context("华尔街见闻文章请求失败")?
            .json().await
            .context("华尔街见闻文章解析失败")?;

        if resp.code != Some(20000) {
            return Err(anyhow::anyhow!("华尔街见闻文章API错误: {:?}", resp.code));
        }

        let items = resp.data.and_then(|d| d.items).unwrap_or_default();
        let now = chrono::Local::now().timestamp();

        let results: Vec<SearchResult> = items.into_iter()
            .filter_map(|item| {
                let title = item.title.filter(|t| !t.is_empty())?;
                if let Some(ts) = item.display_time {
                    if now - ts > 24 * 3600 { return None; }
                }
                let snippet = item.summary.unwrap_or_default();
                let uri = item.content_uri.unwrap_or_default();
                let url = if uri.starts_with("http") { uri } else {
                    format!("https://wallstreetcn.com/articles/{}", uri)
                };
                let date_tag = item.display_time.map(|ts| {
                    let dt = chrono::DateTime::from_timestamp(ts, 0)
                        .unwrap_or_default()
                        .with_timezone(&chrono::Local);
                    dt.format("%H:%M").to_string()
                });
                Some(SearchResult::new(title, snippet, url, "华尔街见闻".to_string())
                    .with_date(date_tag.unwrap_or_default()))
            })
            .collect();

        Ok(results)
    }
}

#[async_trait]
impl SearchProvider for WallStreetCnProvider {
    fn name(&self) -> &str { &self.name }
    fn is_available(&self) -> bool { true }

    async fn search(&self, query: &str, max_results: usize) -> SearchResponse {
        let start = Instant::now();
        // 搜索逻辑：同时拉快讯和文章，按标题/内容过滤关键词
        let keywords: Vec<&str> = query.split_whitespace()
            .filter(|w| w.len() >= 2)
            .take(5)
            .collect();

        let (live_res, article_res) = tokio::join!(
            self.fetch_live_news(30),
            self.fetch_articles(20),
        );

        let mut all: Vec<SearchResult> = Vec::new();
        if let Ok(items) = live_res { all.extend(items); }
        if let Ok(items) = article_res { all.extend(items); }

        // 过滤相关条目
        let filtered: Vec<SearchResult> = if keywords.is_empty() {
            all.into_iter().take(max_results).collect()
        } else {
            all.into_iter()
                .filter(|r| {
                    let text = format!("{} {}", r.title, r.snippet).to_lowercase();
                    keywords.iter().any(|kw| text.contains(&kw.to_lowercase()))
                })
                .take(max_results)
                .collect()
        };

        let success = !filtered.is_empty();
        SearchResponse {
            query: query.to_string(),
            results: filtered,
            provider: self.name.clone(),
            success,
            error_message: if success { None } else { Some("无相关结果".to_string()) },
            search_time: start.elapsed().as_secs_f64(),
        }
    }
}

